### PR TITLE
Spanish language is added to the translations

### PR DESCRIPTION
**Pull request by mapeveri**

### CODE REVIEW

**Comment by optiroot** [comment]
Thank you for your pull request! I noticed you fixed the unlocalized string too.
Just for clearness, is this translation created manually or with a software translator like Google Translate?

I ask to be completely sure so I can accept the PR.
Thank you.

**Comment by mapeveri** [comment]
@optiroot I don't understand this "I noticed you fixed the unlocalized string too".
A mix, I used the google translator for some doubts. Some things google translate, translate wrong, then I corrected them and others I translated without using the translator.

Thanks!

**Comment by optiroot** [comment]
Thank you for the explanation!

You noticed the unlocalized "Latest URLs" in the **nav.blade.php** file [here](https://github.com/urlhum/UrlHum/pull/3/commits/b5ecf6890ea9f5c79152c49ce37e6da4d5a78219#diff-d2d611c8b6201c4558271ac600036715) and fixed it!

Thanks so much! 
Merged.

**Comment by mapeveri** [comment]
@optiroot ahh yes!. 

Great!

If there is an issue that can help, let me know :)

**Pull request merged**
